/**
 * @author Kuitos
 * @since 2019-10-21
 */
import { execScripts } from 'import-html-entry';
import { isFunction } from 'lodash';
import { frameworkConfiguration } from '../../../apis';
import { qiankunHeadTagName } from '../../../utils';
import { cachedGlobals } from '../../proxySandbox';
import * as css from '../css';
const SCRIPT_TAG_NAME = 'SCRIPT';
const LINK_TAG_NAME = 'LINK';
const STYLE_TAG_NAME = 'STYLE';
export const styleElementTargetSymbol = Symbol('target');
export const styleElementRefNodeNo = Symbol('refNodeNo');
const overwrittenSymbol = Symbol('qiankun-overwritten');
// 获取 qiankun-head 标签元素
export const getAppWrapperHeadElement = (appWrapper) => {
  return appWrapper.querySelector(qiankunHeadTagName);
};
export function isExecutableScriptType(script) {
  // 如果 script 标签没有 type 属性，或者 type 属性是 text/javascript、module、application/javascript、text/ecmascript、application/ecmascript，则返回 true
  return (
    !script.type ||
    ['text/javascript', 'module', 'application/javascript', 'text/ecmascript', 'application/ecmascript'].indexOf(
      script.type,
    ) !== -1
  );
}
// 是否是需要劫持的标签，包括 LINK、STYLE、SCRIPT
export function isHijackingTag(tagName) {
  return (
    tagName?.toUpperCase() === LINK_TAG_NAME ||
    tagName?.toUpperCase() === STYLE_TAG_NAME ||
    tagName?.toUpperCase() === SCRIPT_TAG_NAME
  );
}
/**
 * Check if a style element is a styled-component liked.
 * A styled-components liked element is which not have textContext but keep the rules in its styleSheet.cssRules.
 * Such as the style element generated by styled-components and emotion.
 * @param element
 */
export function isStyledComponentsLike(element) {
  return !element.textContent && (element.sheet?.cssRules.length || getStyledElementCSSRules(element)?.length);
}
const appsCounterMap = new Map();
// 计算 patch 的数量
export function calcAppCount(appName, calcType, status) {
  // 获取 appName 对应的 appCount, 默认为 { bootstrappingPatchCount: 0, mountingPatchCount: 0 }
  const appCount = appsCounterMap.get(appName) || { bootstrappingPatchCount: 0, mountingPatchCount: 0 };
  // 根据 calcType 计算 patch 的数量
  switch (calcType) {
    case 'increase':
      appCount[`${status}PatchCount`] += 1;
      break;
    case 'decrease':
      // bootstrap patch just called once but its freer will be called multiple times
      if (appCount[`${status}PatchCount`] > 0) {
        appCount[`${status}PatchCount`] -= 1;
      }
      break;
  }
  appsCounterMap.set(appName, appCount);
}
export function isAllAppsUnmounted() {
  // 如果所有的 app 的 bootstrappingPatchCount 和 mountingPatchCount 都为 0，则返回 true
  return Array.from(appsCounterMap.entries()).every(
    ([, { bootstrappingPatchCount: bpc, mountingPatchCount: mpc }]) => bpc === 0 && mpc === 0,
  );
}
function patchCustomEvent(e, elementGetter) {
  // defineProperties 用于定义属性
  Object.defineProperties(e, {
    srcElement: {
      get: elementGetter,
    },
    target: {
      get: elementGetter,
    },
  });
  return e;
}
function manualInvokeElementOnLoad(element) {
  // we need to invoke the onload event manually to notify the event listener that the script was completed
  // here are the two typical ways of dynamic script loading
  // 1. element.onload callback way, which webpack and loadjs used, see https://github.com/muicss/loadjs/blob/master/src/loadjs.js#L138
  // 2. addEventListener way, which toast-loader used, see https://github.com/pyrsmk/toast/blob/master/src/Toast.ts#L64

  // 我们需要手动调用 onload 事件来通知事件监听器脚本已完成
  // 这里有两种动态加载脚本的典型方式
  // 1. element.onload 回调方式，webpack 和 loadjs 使用了这种方式，参见 https://github.com/kubetail-org/loadjs/blob/main/src/loadjs.js#L138
  // 2. addEventListener 方式，toast-loader 使用了这种方式，参见 https://github.com/pyrsmk/toast/blob/master/src/Toast.ts#L64

  // 创建一个 load 的 CustomEvent 事件
  const loadEvent = new CustomEvent('load');
  // 对 loadEvent 进行处理，主要是将 srcElement 和 target 设置为 element
  const patchedEvent = patchCustomEvent(loadEvent, () => element);
  // 如果 element 上有 onload 方法，则调用 onload 方法
  if (isFunction(element.onload)) {
    element.onload(patchedEvent);
  } else {
    // 否则手动调用 onload 事件
    element.dispatchEvent(patchedEvent);
  }
}
function manualInvokeElementOnError(element) {
  // 创建一个 error 的 CustomEvent 事件
  const errorEvent = new CustomEvent('error');
  // 对 errorEvent 进行处理，主要是将 srcElement 和 target 设置为 element
  const patchedEvent = patchCustomEvent(errorEvent, () => element);
  // 如果 element 上有 onerror 方法，则调用 onerror 方法
  if (isFunction(element.onerror)) {
    element.onerror(patchedEvent);
  } else {
    // 否则手动调用 onerror 事件
    element.dispatchEvent(patchedEvent);
  }
}
function convertLinkAsStyle(element, postProcess, fetchFn = fetch) {
  // 创建一个内联 Style 标签
  const styleElement = document.createElement('style');
  // 获取 LINK 标签的 href 属性
  const { href } = element;
  // add source link element href
  // 将 LINK 标签的 href 属性添加到 styleElement 上
  styleElement.dataset.qiankunHref = href;
  // 请求 LINK 标签的 href 属性
  fetchFn(href)
    .then((res) => res.text())
    .then((styleContext) => {
      // 将 LINK 标签获取的内容添加到 styleElement 上
      styleElement.appendChild(document.createTextNode(styleContext));
      // 对样式进行 Scope 处理
      postProcess(styleElement);
      // 手动调用 onload 事件
      manualInvokeElementOnLoad(element);
    })
    .catch(() => manualInvokeElementOnError(element));
  // 返回内联 Style 标签
  return styleElement;
}
// 定义需要添加的 element 元素不可枚举
const defineNonEnumerableProperty = (target, key, value) => {
  Object.defineProperty(target, key, {
    configurable: true,
    enumerable: false,
    writable: true,
    value,
  });
};
const styledComponentCSSRulesMap = new WeakMap();
const dynamicScriptAttachedCommentMap = new WeakMap();
const dynamicLinkAttachedInlineStyleMap = new WeakMap();
// 记录 styled-components 的 CSS 规则
export function recordStyledComponentsCSSRules(styleElements) {
  styleElements.forEach((styleElement) => {
    /*
         With a styled-components generated style element, we need to record its cssRules for restore next re-mounting time.
         We're doing this because the sheet of style element is going to be cleaned automatically by browser after the style element dom removed from document.
         see https://www.w3.org/TR/cssom-1/#associated-css-style-sheet
         */
    //
    if (styleElement instanceof HTMLStyleElement && isStyledComponentsLike(styleElement)) {
      if (styleElement.sheet) {
        // record the original css rules of the style element for restore
        styledComponentCSSRulesMap.set(styleElement, styleElement.sheet.cssRules);
      }
    }
  });
}
export function getStyledElementCSSRules(styledElement) {
  return styledComponentCSSRulesMap.get(styledElement);
}
function getOverwrittenAppendChildOrInsertBefore(opts) {
  // 重写 appendChild 或 insertBefore 方法
  // 在 insertBefore 方法中，newChild 是要插入的节点，refChild 用于将 newChild 插入到 refChild 之前
  // 在 appendChild 方法中，newChild 是要插入的节点，refChild 为 null
  function appendChildOrInsertBefore(newChild, refChild = null) {
    // 获取要添加的节点
    let element = newChild;
    // rawDOMAppendOrInsertBefore: 原始的 appendChild 或 insertBefore 方法
    // isInvokedByMicroApp: 是否是子应用调用
    // containerConfigGetter: proxy 对应的 containerConfig
    // target: 目标容器, head 或 body
    const { rawDOMAppendOrInsertBefore, isInvokedByMicroApp, containerConfigGetter, target = 'body' } = opts;
    // 1. 如果不是 LINK、STYLE、SCRIPT 标签，则不需要劫持处理
    // 2. 如果不是子应用调用，则不需要劫持处理
    if (!isHijackingTag(element.tagName) || !isInvokedByMicroApp(element)) {
      return rawDOMAppendOrInsertBefore.call(this, element, refChild);
    }
    // 如果是 LINK、STYLE、SCRIPT 标签
    if (element.tagName) {
      // 获取 proxy 对应的 containerConfig
      const containerConfig = containerConfigGetter(element);
      const {
        appName,
        appWrapperGetter,
        proxy,
        strictGlobal,
        speedySandbox,
        dynamicStyleSheetElements,
        scopedCSS,
        excludeAssetFilter,
      } = containerConfig;
      switch (element.tagName) {
        // 如果是 STYLE 或者 LINK 标签
        case LINK_TAG_NAME:
        case STYLE_TAG_NAME: {
          let stylesheetElement = newChild;
          // 获取 LINK 标签的 href 属性
          const { href } = stylesheetElement;
          // 如果是 LINK 标签，并且 href 存在，并且 excludeAssetFilter 返回 true，则不需要劫持处理
          if (excludeAssetFilter && href && excludeAssetFilter(href)) {
            return rawDOMAppendOrInsertBefore.call(this, element, refChild);
          }
          // stylesheetElement: 需要添加的标签
          // styleElementTargetSymbol: Symbol('target')
          // target 为 head 或 body
          // 将 target 设置到 stylesheetElement 上
          defineNonEnumerableProperty(stylesheetElement, styleElementTargetSymbol, target);
          // 获取微应用的容器元素
          const appWrapper = appWrapperGetter();
          // 如果是 LINK 标签，并且 scopedCSS 为 true
          if (scopedCSS) {
            // exclude link elements like <link rel="icon" href="favicon.ico">
            // 如果是 LINK 标签，并且 rel 为  stylesheet，并且 href 存在，则需要劫持处理
            const linkElementUsingStylesheet =
              element.tagName?.toUpperCase() === LINK_TAG_NAME && element.rel === 'stylesheet' && element.href;
            if (linkElementUsingStylesheet) {
              // 获取 fetch 方法
              const fetch =
                typeof frameworkConfiguration.fetch === 'function'
                  ? frameworkConfiguration.fetch
                  : frameworkConfiguration.fetch?.fn;
              // 将外链 Link 标签转换为内联 Style 标签
              stylesheetElement = convertLinkAsStyle(
                // 需要添加的标签
                element,
                // postProcess，对样式进行 Scope 处理
                (styleElement) => css.process(appWrapper, styleElement, appName),
                // fetch 方法
                fetch,
              );
              dynamicLinkAttachedInlineStyleMap.set(element, stylesheetElement);
            } else {
              // 否则处理内联样式，对样式进行 Scope 处理
              css.process(appWrapper, stylesheetElement, appName);
            }
          }
          // 如果目标是 head，则获取微应用的 qiankun-head 元素
          // 否则获取微应用的容器元素
          const mountDOM = target === 'head' ? getAppWrapperHeadElement(appWrapper) : appWrapper;
          // 如果 refChild 存在，则获取 refChild 的索引
          const referenceNode = mountDOM.contains(refChild) ? refChild : null;
          let refNo;
          if (referenceNode) {
            // 判断 refChild 是否存在于 mountDOM 中
            refNo = Array.from(mountDOM.childNodes).indexOf(referenceNode);
          }
          // 使用原始的 appendChild 或 insertBefore 方法将处理了内联 Scope 样式的 stylesheetElement 添加到 mountDOM 中
          const result = rawDOMAppendOrInsertBefore.call(mountDOM, stylesheetElement, referenceNode);
          // record refNo thus we can keep order while remounting
          // 如果 refChild 存在，则将 refNo 设置到 stylesheetElement 上
          if (typeof refNo === 'number' && refNo !== -1) {
            // 在 stylesheetElement 上设置 refNodeNo 属性
            defineNonEnumerableProperty(stylesheetElement, styleElementRefNodeNo, refNo);
          }
          // record dynamic style elements after insert succeed
          // 记录动态样式表元素
          dynamicStyleSheetElements.push(stylesheetElement);
          return result;
        }
        // 如果是 SCRIPT 标签
        case SCRIPT_TAG_NAME: {
          // 获取 SCRIPT 标签的 src 和 text 属性
          const { src, text } = element;
          // some script like jsonp maybe not support cors which shouldn't use execScripts
          // 一些脚本（如 jsonp）可能不支持跨域，不应该使用 execScripts
          // 如果 excludeAssetFilter 存在，并且 src 存在，并且 excludeAssetFilter 返回 true，则不需要劫持处理
          // 如果不是可执行的脚本类型，则不需要劫持处理
          if ((excludeAssetFilter && src && excludeAssetFilter(src)) || !isExecutableScriptType(element)) {
            // 使用原始的 appendChild 或 insertBefore 方法将 element 添加到 mountDOM 中
            return rawDOMAppendOrInsertBefore.call(this, element, refChild);
          }
          // 获取微应用的容器元素
          const appWrapper = appWrapperGetter();
          // 如果 target 是 head，则获取微应用的 qiankun-head 元素
          // 否则获取微应用的容器元素
          const mountDOM = target === 'head' ? getAppWrapperHeadElement(appWrapper) : appWrapper;
          // 获取 fetch 方法
          const { fetch } = frameworkConfiguration;
          // 如果 refChild 存在，则获取 refChild 的索引
          const referenceNode = mountDOM.contains(refChild) ? refChild : null;
          // 如果开启了速度沙箱，则使用缓存的全局变量，例如 "Array"、"Date"、"JSON"、"Math"、"Object"、"Promise"、"Proxy"、"Reflect"、"RegExp"、"Symbol"、"TypeError"、"WeakMap"、"WeakSet" 等
          // 如果使用 with 包裹，那么可以缩短变量查找的作用域链
          // 例如在 import-html-entry 中，使用 with 包裹了沙箱的代理对象，这样就可以直接访问沙箱的代理对象，而不需要通过作用域链查找
          // 例如：const scopedGlobalVariableDefinition = scopedGlobalVariables.length ? `const {${scopedGlobalVariables.join(',')}}=this;` : '';
          // `;(function(){with(this){${scopedGlobalVariableDefinition}${scriptText}\n${sourceUrl}}}).bind(window.proxy)();`

          // 即 with(this) { const { Array } = this; // 接下来微应用代码中使用 Array 直接使用局部变量 Array， 缩短了作用域链的查找 }
          const scopedGlobalVariables = speedySandbox ? cachedGlobals : [];
          // 如果 src 存在，则使用 execScripts 方法执行脚本
          if (src) {
            let isRedfinedCurrentScript = false;
            // 使用 execScripts 方法执行脚本
            // 传入代理的 proxy 进行沙箱隔离
            execScripts(null, [src], proxy, {
              fetch,
              strictGlobal,
              scopedGlobalVariables,
              // beforeExec: 在执行脚本之前执行
              beforeExec: () => {
                const isCurrentScriptConfigurable = () => {
                  // document.currentScript 属性返回正在执行的 script 元素
                  // 如果 document 上没有 currentScript 属性，或者 currentScript 属性是可配置的，则返回 true
                  const descriptor = Object.getOwnPropertyDescriptor(document, 'currentScript');
                  return !descriptor || descriptor.configurable;
                };
                // 如果 currentScript 属性是可配置的，则重写 currentScript 属性
                if (isCurrentScriptConfigurable()) {
                  Object.defineProperty(document, 'currentScript', {
                    get() {
                      // 需要添加的标签
                      return element;
                    },
                    configurable: true,
                  });
                  // 设置重写标记
                  isRedfinedCurrentScript = true;
                }
              },
              // success: 执行成功
              success: () => {
                // 执行成功后，手动调用 onload 事件
                manualInvokeElementOnLoad(element);
                // 如果 currentScript 属性是可配置的，则删除 currentScript 属性
                if (isRedfinedCurrentScript) {
                  // @ts-ignore
                  delete document.currentScript;
                }
                element = null;
              },
              error: () => {
                // 执行失败后，手动调用 onerror 事件
                manualInvokeElementOnError(element);
                if (isRedfinedCurrentScript) {
                  // @ts-ignore
                  delete document.currentScript;
                }
                element = null;
              },
            });
            // 动态创建一个注释节点，用于替换当前 SCRIPT 标签
            const dynamicScriptCommentElement = document.createComment(`dynamic script ${src} replaced by qiankun`);
            // 将动态创建的注释节点添加到 map 中
            dynamicScriptAttachedCommentMap.set(element, dynamicScriptCommentElement);
            // 使用原始的 appendChild 或 insertBefore 方法将动态创建的注释节点添加到 mountDOM 中
            return rawDOMAppendOrInsertBefore.call(mountDOM, dynamicScriptCommentElement, referenceNode);
          }
          // inline script never trigger the onload and onerror event
          // 如果是内联脚本，则隔离执行脚本
          execScripts(null, [`<script>${text}</script>`], proxy, { strictGlobal, scopedGlobalVariables });
          // 创建一个注释节点，用于替换当前 SCRIPT 标签
          const dynamicInlineScriptCommentElement = document.createComment('dynamic inline script replaced by qiankun');
          // 将动态创建的注释节点添加到 map 中
          dynamicScriptAttachedCommentMap.set(element, dynamicInlineScriptCommentElement);
          // 使用原始的 appendChild 或 insertBefore 方法将动态创建的注释节点添加到 mountDOM 中
          return rawDOMAppendOrInsertBefore.call(mountDOM, dynamicInlineScriptCommentElement, referenceNode);
        }
        default:
          break;
      }
    }
    // 否则使用原始的 appendChild 或 insertBefore 方法将 element 添加到 mountDOM 中
    return rawDOMAppendOrInsertBefore.call(this, element, refChild);
  }
  // 设置重写标记，表明已经被重写
  appendChildOrInsertBefore[overwrittenSymbol] = true;
  return appendChildOrInsertBefore;
}
function getNewRemoveChild(rawRemoveChild, containerConfigGetter, target, isInvokedByMicroApp) {
  function removeChild(child) {
    const { tagName } = child;
    // 如果不是 LINK、STYLE、SCRIPT 标签，则不需要劫持处理
    if (!isHijackingTag(tagName) || !isInvokedByMicroApp(child)) return rawRemoveChild.call(this, child);
    try {
      let attachedElement;
      // 1. appWrapperGetter: 获取微应用的容器元素
      // 2. dynamicStyleSheetElements: 动态样式表元素
      const { appWrapperGetter, dynamicStyleSheetElements } = containerConfigGetter(child);
      switch (tagName) {
        // 如果是 LINK、STYLE 标签
        case STYLE_TAG_NAME:
        case LINK_TAG_NAME: {
          // 获取 LINK 或 STYLE 标签的 element
          attachedElement = dynamicLinkAttachedInlineStyleMap.get(child) || child;
          // try to remove the dynamic style sheet
          // 计算相应的索引
          const dynamicElementIndex = dynamicStyleSheetElements.indexOf(attachedElement);
          // 去除动态样式表元素
          if (dynamicElementIndex !== -1) {
            dynamicStyleSheetElements.splice(dynamicElementIndex, 1);
          }
          break;
        }
        case SCRIPT_TAG_NAME: {
          attachedElement = dynamicScriptAttachedCommentMap.get(child) || child;
          break;
        }
        default: {
          attachedElement = child;
        }
      }
      // 获取微应用的容器元素
      const appWrapper = appWrapperGetter();
      // 如果是 head，则获取微应用的 qiankun-head 元素
      // 否则获取微应用的容器元素
      const container = target === 'head' ? getAppWrapperHeadElement(appWrapper) : appWrapper;
      // container might have been removed while app unmounting if the removeChild action was async
      // 如果 container 没有被移除，则使用原始的 removeChild 方法将 attachedElement 从 container 中移除
      if (container.contains(attachedElement)) {
        return rawRemoveChild.call(attachedElement.parentNode, attachedElement);
      }
    } catch (e) {
      console.warn(e);
    }
    // 否则使用原始的 removeChild 方法将 child 从 container 中移除
    return rawRemoveChild.call(this, child);
  }
  // 设置重写标记，表明已经被重写
  removeChild[overwrittenSymbol] = true;
  return removeChild;
}

// 如果是通过 JavaScript 脚本动态添加的 LINK、STYLE、SCRIPT 标签，则需要劫持处理
// isInvokedByMicroApp: 是否是子应用调用
// containerConfigGetter: 获取容器配置
export function patchHTMLDynamicAppendPrototypeFunctions(isInvokedByMicroApp, containerConfigGetter) {
  // 重写 head 和 body 的 appendChild 方法
  const rawHeadAppendChild = HTMLHeadElement.prototype.appendChild;
  const rawBodyAppendChild = HTMLBodyElement.prototype.appendChild;
  // 重写 head 的 insertBefore 方法
  const rawHeadInsertBefore = HTMLHeadElement.prototype.insertBefore;
  // Just overwrite it while it have not been overwritten
  // 如果没有被重写，则重写
  if (
    rawHeadAppendChild[overwrittenSymbol] !== true &&
    rawBodyAppendChild[overwrittenSymbol] !== true &&
    rawHeadInsertBefore[overwrittenSymbol] !== true
  ) {
    // 重写 head 的 appendChild 方法
    HTMLHeadElement.prototype.appendChild = getOverwrittenAppendChildOrInsertBefore({
      // 原始的 appendChild 方法
      rawDOMAppendOrInsertBefore: rawHeadAppendChild,
      // 获取容器配置
      // elementAttachContainerConfigMap, key 是 element，value 是 proxy containerConfig
      // (element) => elementAttachContainerConfigMap.get(element),
      containerConfigGetter,
      // 是否是子应用调用
      // (element) => elementAttachContainerConfigMap.has(element),
      isInvokedByMicroApp,
      target: 'head',
    });
    // 重写 body 的 appendChild 方法
    HTMLBodyElement.prototype.appendChild = getOverwrittenAppendChildOrInsertBefore({
      rawDOMAppendOrInsertBefore: rawBodyAppendChild,
      containerConfigGetter,
      isInvokedByMicroApp,
      target: 'body',
    });
    // 重写 head 的 insertBefore 方法
    HTMLHeadElement.prototype.insertBefore = getOverwrittenAppendChildOrInsertBefore({
      rawDOMAppendOrInsertBefore: rawHeadInsertBefore,
      containerConfigGetter,
      isInvokedByMicroApp,
      target: 'head',
    });
  }

  // 重写 head 和 body 的 removeChild 方法
  const rawHeadRemoveChild = HTMLHeadElement.prototype.removeChild;
  const rawBodyRemoveChild = HTMLBodyElement.prototype.removeChild;
  // Just overwrite it while it have not been overwritten
  // 如果没有被重写，则重写
  if (rawHeadRemoveChild[overwrittenSymbol] !== true && rawBodyRemoveChild[overwrittenSymbol] !== true) {
    HTMLHeadElement.prototype.removeChild = getNewRemoveChild(
      rawHeadRemoveChild,
      containerConfigGetter,
      'head',
      isInvokedByMicroApp,
    );
    HTMLBodyElement.prototype.removeChild = getNewRemoveChild(
      rawBodyRemoveChild,
      containerConfigGetter,
      'body',
      isInvokedByMicroApp,
    );
  }
  // 返回一个函数，用于释放重写的方法
  return function unpatch() {
    HTMLHeadElement.prototype.appendChild = rawHeadAppendChild;
    HTMLHeadElement.prototype.removeChild = rawHeadRemoveChild;
    HTMLBodyElement.prototype.appendChild = rawBodyAppendChild;
    HTMLBodyElement.prototype.removeChild = rawBodyRemoveChild;
    HTMLHeadElement.prototype.insertBefore = rawHeadInsertBefore;
  };
}
export function rebuildCSSRules(styleSheetElements, reAppendElement) {
  styleSheetElements.forEach((stylesheetElement) => {
    // re-append the dynamic stylesheet to sub-app container
    const appendSuccess = reAppendElement(stylesheetElement);
    if (appendSuccess) {
      /*
            get the stored css rules from styled-components generated element, and the re-insert rules for them.
            note that we must do this after style element had been added to document, which stylesheet would be associated to the document automatically.
            check the spec https://www.w3.org/TR/cssom-1/#associated-css-style-sheet
             */
      if (stylesheetElement instanceof HTMLStyleElement && isStyledComponentsLike(stylesheetElement)) {
        const cssRules = getStyledElementCSSRules(stylesheetElement);
        if (cssRules) {
          // eslint-disable-next-line no-plusplus
          for (let i = 0; i < cssRules.length; i++) {
            const cssRule = cssRules[i];
            const cssStyleSheetElement = stylesheetElement.sheet;
            cssStyleSheetElement.insertRule(cssRule.cssText, cssStyleSheetElement.cssRules.length);
          }
        }
      }
    }
  });
}
