import { without } from "lodash";

// generated from https://github.com/sindresorhus/globals/blob/main/globals.json es2015 part
// only init its values while Proxy is supported
export const globalsInES2015 = window.Proxy
  ? [
      "Array",
      "ArrayBuffer",
      "Boolean",
      "constructor",
      "DataView",
      "Date",
      "decodeURI",
      "decodeURIComponent",
      "encodeURI",
      "encodeURIComponent",
      "Error",
      "escape",
      "eval",
      "EvalError",
      "Float32Array",
      "Float64Array",
      "Function",
      "hasOwnProperty",
      "Infinity",
      "Int16Array",
      "Int32Array",
      "Int8Array",
      "isFinite",
      "isNaN",
      "isPrototypeOf",
      "JSON",
      "Map",
      "Math",
      "NaN",
      "Number",
      "Object",
      "parseFloat",
      "parseInt",
      "Promise",
      "propertyIsEnumerable",
      "Proxy",
      "RangeError",
      "ReferenceError",
      "Reflect",
      "RegExp",
      "Set",
      "String",
      "Symbol",
      "SyntaxError",
      "toLocaleString",
      "toString",
      "TypeError",
      "Uint16Array",
      "Uint32Array",
      "Uint8Array",
      "Uint8ClampedArray",
      "undefined",
      "unescape",
      "URIError",
      "valueOf",
      "WeakMap",
      "WeakSet",
    ].filter(
      (p) =>
        /* just keep the available properties in current window context */ p in
        window
    )
  : [];

export const globalsInBrowser = [
  "AbortController",
  "AbortSignal",
  "addEventListener",
  "alert",
  "AnalyserNode",
  "Animation",
  "AnimationEffectReadOnly",
  "AnimationEffectTiming",
  "AnimationEffectTimingReadOnly",
  "AnimationEvent",
  "AnimationPlaybackEvent",
  "AnimationTimeline",
  "applicationCache",
  "ApplicationCache",
  "ApplicationCacheErrorEvent",
  "atob",
  "Attr",
  "Audio",
  "AudioBuffer",
  "AudioBufferSourceNode",
  "AudioContext",
  "AudioDestinationNode",
  "AudioListener",
  "AudioNode",
  "AudioParam",
  "AudioProcessingEvent",
  "AudioScheduledSourceNode",
  "AudioWorkletGlobalScope",
  "AudioWorkletNode",
  "AudioWorkletProcessor",
  "BarProp",
  "BaseAudioContext",
  "BatteryManager",
  "BeforeUnloadEvent",
  "BiquadFilterNode",
  "Blob",
  "BlobEvent",
  "blur",
  "BroadcastChannel",
  "btoa",
  "BudgetService",
  "ByteLengthQueuingStrategy",
  "Cache",
  "caches",
  "CacheStorage",
  "cancelAnimationFrame",
  "cancelIdleCallback",
  "CanvasCaptureMediaStreamTrack",
  "CanvasGradient",
  "CanvasPattern",
  "CanvasRenderingContext2D",
  "ChannelMergerNode",
  "ChannelSplitterNode",
  "CharacterData",
  "clearInterval",
  "clearTimeout",
  "clientInformation",
  "ClipboardEvent",
  "ClipboardItem",
  "close",
  "closed",
  "CloseEvent",
  "Comment",
  "CompositionEvent",
  "CompressionStream",
  "confirm",
  "console",
  "ConstantSourceNode",
  "ConvolverNode",
  "CountQueuingStrategy",
  "createImageBitmap",
  "Credential",
  "CredentialsContainer",
  "crypto",
  "Crypto",
  "CryptoKey",
  "CSS",
  "CSSConditionRule",
  "CSSFontFaceRule",
  "CSSGroupingRule",
  "CSSImportRule",
  "CSSKeyframeRule",
  "CSSKeyframesRule",
  "CSSMatrixComponent",
  "CSSMediaRule",
  "CSSNamespaceRule",
  "CSSPageRule",
  "CSSPerspective",
  "CSSRotate",
  "CSSRule",
  "CSSRuleList",
  "CSSScale",
  "CSSSkew",
  "CSSSkewX",
  "CSSSkewY",
  "CSSStyleDeclaration",
  "CSSStyleRule",
  "CSSStyleSheet",
  "CSSSupportsRule",
  "CSSTransformValue",
  "CSSTranslate",
  "CustomElementRegistry",
  "customElements",
  "CustomEvent",
  "DataTransfer",
  "DataTransferItem",
  "DataTransferItemList",
  "DecompressionStream",
  "defaultstatus",
  "defaultStatus",
  "DelayNode",
  "DeviceMotionEvent",
  "DeviceOrientationEvent",
  "devicePixelRatio",
  "dispatchEvent",
  "document",
  "Document",
  "DocumentFragment",
  "DocumentType",
  "DOMError",
  "DOMException",
  "DOMImplementation",
  "DOMMatrix",
  "DOMMatrixReadOnly",
  "DOMParser",
  "DOMPoint",
  "DOMPointReadOnly",
  "DOMQuad",
  "DOMRect",
  "DOMRectList",
  "DOMRectReadOnly",
  "DOMStringList",
  "DOMStringMap",
  "DOMTokenList",
  "DragEvent",
  "DynamicsCompressorNode",
  "Element",
  "ErrorEvent",
  "event",
  "Event",
  "EventSource",
  "EventTarget",
  "external",
  "fetch",
  "File",
  "FileList",
  "FileReader",
  "find",
  "focus",
  "FocusEvent",
  "FontFace",
  "FontFaceSetLoadEvent",
  "FormData",
  "FormDataEvent",
  "frameElement",
  "frames",
  "GainNode",
  "Gamepad",
  "GamepadButton",
  "GamepadEvent",
  "getComputedStyle",
  "getSelection",
  "HashChangeEvent",
  "Headers",
  "history",
  "History",
  "HTMLAllCollection",
  "HTMLAnchorElement",
  "HTMLAreaElement",
  "HTMLAudioElement",
  "HTMLBaseElement",
  "HTMLBodyElement",
  "HTMLBRElement",
  "HTMLButtonElement",
  "HTMLCanvasElement",
  "HTMLCollection",
  "HTMLContentElement",
  "HTMLDataElement",
  "HTMLDataListElement",
  "HTMLDetailsElement",
  "HTMLDialogElement",
  "HTMLDirectoryElement",
  "HTMLDivElement",
  "HTMLDListElement",
  "HTMLDocument",
  "HTMLElement",
  "HTMLEmbedElement",
  "HTMLFieldSetElement",
  "HTMLFontElement",
  "HTMLFormControlsCollection",
  "HTMLFormElement",
  "HTMLFrameElement",
  "HTMLFrameSetElement",
  "HTMLHeadElement",
  "HTMLHeadingElement",
  "HTMLHRElement",
  "HTMLHtmlElement",
  "HTMLIFrameElement",
  "HTMLImageElement",
  "HTMLInputElement",
  "HTMLLabelElement",
  "HTMLLegendElement",
  "HTMLLIElement",
  "HTMLLinkElement",
  "HTMLMapElement",
  "HTMLMarqueeElement",
  "HTMLMediaElement",
  "HTMLMenuElement",
  "HTMLMetaElement",
  "HTMLMeterElement",
  "HTMLModElement",
  "HTMLObjectElement",
  "HTMLOListElement",
  "HTMLOptGroupElement",
  "HTMLOptionElement",
  "HTMLOptionsCollection",
  "HTMLOutputElement",
  "HTMLParagraphElement",
  "HTMLParamElement",
  "HTMLPictureElement",
  "HTMLPreElement",
  "HTMLProgressElement",
  "HTMLQuoteElement",
  "HTMLScriptElement",
  "HTMLSelectElement",
  "HTMLShadowElement",
  "HTMLSlotElement",
  "HTMLSourceElement",
  "HTMLSpanElement",
  "HTMLStyleElement",
  "HTMLTableCaptionElement",
  "HTMLTableCellElement",
  "HTMLTableColElement",
  "HTMLTableElement",
  "HTMLTableRowElement",
  "HTMLTableSectionElement",
  "HTMLTemplateElement",
  "HTMLTextAreaElement",
  "HTMLTimeElement",
  "HTMLTitleElement",
  "HTMLTrackElement",
  "HTMLUListElement",
  "HTMLUnknownElement",
  "HTMLVideoElement",
  "IDBCursor",
  "IDBCursorWithValue",
  "IDBDatabase",
  "IDBFactory",
  "IDBIndex",
  "IDBKeyRange",
  "IDBObjectStore",
  "IDBOpenDBRequest",
  "IDBRequest",
  "IDBTransaction",
  "IDBVersionChangeEvent",
  "IdleDeadline",
  "IIRFilterNode",
  "Image",
  "ImageBitmap",
  "ImageBitmapRenderingContext",
  "ImageCapture",
  "ImageData",
  "indexedDB",
  "innerHeight",
  "innerWidth",
  "InputEvent",
  "IntersectionObserver",
  "IntersectionObserverEntry",
  "Intl",
  "isSecureContext",
  "KeyboardEvent",
  "KeyframeEffect",
  "KeyframeEffectReadOnly",
  "length",
  "localStorage",
  "location",
  "Location",
  "locationbar",
  "matchMedia",
  "MediaDeviceInfo",
  "MediaDevices",
  "MediaElementAudioSourceNode",
  "MediaEncryptedEvent",
  "MediaError",
  "MediaKeyMessageEvent",
  "MediaKeySession",
  "MediaKeyStatusMap",
  "MediaKeySystemAccess",
  "MediaList",
  "MediaMetadata",
  "MediaQueryList",
  "MediaQueryListEvent",
  "MediaRecorder",
  "MediaSettingsRange",
  "MediaSource",
  "MediaStream",
  "MediaStreamAudioDestinationNode",
  "MediaStreamAudioSourceNode",
  "MediaStreamConstraints",
  "MediaStreamEvent",
  "MediaStreamTrack",
  "MediaStreamTrackEvent",
  "menubar",
  "MessageChannel",
  "MessageEvent",
  "MessagePort",
  "MIDIAccess",
  "MIDIConnectionEvent",
  "MIDIInput",
  "MIDIInputMap",
  "MIDIMessageEvent",
  "MIDIOutput",
  "MIDIOutputMap",
  "MIDIPort",
  "MimeType",
  "MimeTypeArray",
  "MouseEvent",
  "moveBy",
  "moveTo",
  "MutationEvent",
  "MutationObserver",
  "MutationRecord",
  "name",
  "NamedNodeMap",
  "NavigationPreloadManager",
  "navigator",
  "Navigator",
  "NavigatorUAData",
  "NetworkInformation",
  "Node",
  "NodeFilter",
  "NodeIterator",
  "NodeList",
  "Notification",
  "OfflineAudioCompletionEvent",
  "OfflineAudioContext",
  "offscreenBuffering",
  "OffscreenCanvas",
  "OffscreenCanvasRenderingContext2D",
  "onabort",
  "onafterprint",
  "onanimationend",
  "onanimationiteration",
  "onanimationstart",
  "onappinstalled",
  "onauxclick",
  "onbeforeinstallprompt",
  "onbeforeprint",
  "onbeforeunload",
  "onblur",
  "oncancel",
  "oncanplay",
  "oncanplaythrough",
  "onchange",
  "onclick",
  "onclose",
  "oncontextmenu",
  "oncuechange",
  "ondblclick",
  "ondevicemotion",
  "ondeviceorientation",
  "ondeviceorientationabsolute",
  "ondrag",
  "ondragend",
  "ondragenter",
  "ondragleave",
  "ondragover",
  "ondragstart",
  "ondrop",
  "ondurationchange",
  "onemptied",
  "onended",
  "onerror",
  "onfocus",
  "ongotpointercapture",
  "onhashchange",
  "oninput",
  "oninvalid",
  "onkeydown",
  "onkeypress",
  "onkeyup",
  "onlanguagechange",
  "onload",
  "onloadeddata",
  "onloadedmetadata",
  "onloadstart",
  "onlostpointercapture",
  "onmessage",
  "onmessageerror",
  "onmousedown",
  "onmouseenter",
  "onmouseleave",
  "onmousemove",
  "onmouseout",
  "onmouseover",
  "onmouseup",
  "onmousewheel",
  "onoffline",
  "ononline",
  "onpagehide",
  "onpageshow",
  "onpause",
  "onplay",
  "onplaying",
  "onpointercancel",
  "onpointerdown",
  "onpointerenter",
  "onpointerleave",
  "onpointermove",
  "onpointerout",
  "onpointerover",
  "onpointerup",
  "onpopstate",
  "onprogress",
  "onratechange",
  "onrejectionhandled",
  "onreset",
  "onresize",
  "onscroll",
  "onsearch",
  "onseeked",
  "onseeking",
  "onselect",
  "onstalled",
  "onstorage",
  "onsubmit",
  "onsuspend",
  "ontimeupdate",
  "ontoggle",
  "ontransitionend",
  "onunhandledrejection",
  "onunload",
  "onvolumechange",
  "onwaiting",
  "onwheel",
  "open",
  "openDatabase",
  "opener",
  "Option",
  "origin",
  "OscillatorNode",
  "outerHeight",
  "outerWidth",
  "OverconstrainedError",
  "PageTransitionEvent",
  "pageXOffset",
  "pageYOffset",
  "PannerNode",
  "parent",
  "Path2D",
  "PaymentAddress",
  "PaymentRequest",
  "PaymentRequestUpdateEvent",
  "PaymentResponse",
  "performance",
  "Performance",
  "PerformanceEntry",
  "PerformanceLongTaskTiming",
  "PerformanceMark",
  "PerformanceMeasure",
  "PerformanceNavigation",
  "PerformanceNavigationTiming",
  "PerformanceObserver",
  "PerformanceObserverEntryList",
  "PerformancePaintTiming",
  "PerformanceResourceTiming",
  "PerformanceTiming",
  "PeriodicWave",
  "Permissions",
  "PermissionStatus",
  "personalbar",
  "PhotoCapabilities",
  "Plugin",
  "PluginArray",
  "PointerEvent",
  "PopStateEvent",
  "postMessage",
  "Presentation",
  "PresentationAvailability",
  "PresentationConnection",
  "PresentationConnectionAvailableEvent",
  "PresentationConnectionCloseEvent",
  "PresentationConnectionList",
  "PresentationReceiver",
  "PresentationRequest",
  "print",
  "ProcessingInstruction",
  "ProgressEvent",
  "PromiseRejectionEvent",
  "prompt",
  "PushManager",
  "PushSubscription",
  "PushSubscriptionOptions",
  "queueMicrotask",
  "RadioNodeList",
  "Range",
  "ReadableByteStreamController",
  "ReadableStream",
  "ReadableStreamBYOBReader",
  "ReadableStreamBYOBRequest",
  "ReadableStreamDefaultController",
  "ReadableStreamDefaultReader",
  "registerProcessor",
  "RemotePlayback",
  "removeEventListener",
  "reportError",
  "Request",
  "requestAnimationFrame",
  "requestIdleCallback",
  "resizeBy",
  "ResizeObserver",
  "ResizeObserverEntry",
  "resizeTo",
  "Response",
  "RTCCertificate",
  "RTCDataChannel",
  "RTCDataChannelEvent",
  "RTCDtlsTransport",
  "RTCIceCandidate",
  "RTCIceGatherer",
  "RTCIceTransport",
  "RTCPeerConnection",
  "RTCPeerConnectionIceEvent",
  "RTCRtpContributingSource",
  "RTCRtpReceiver",
  "RTCRtpSender",
  "RTCSctpTransport",
  "RTCSessionDescription",
  "RTCStatsReport",
  "RTCTrackEvent",
  "screen",
  "Screen",
  "screenLeft",
  "ScreenOrientation",
  "screenTop",
  "screenX",
  "screenY",
  "ScriptProcessorNode",
  "scroll",
  "scrollbars",
  "scrollBy",
  "scrollTo",
  "scrollX",
  "scrollY",
  "SecurityPolicyViolationEvent",
  "Selection",
  "self",
  "ServiceWorker",
  "ServiceWorkerContainer",
  "ServiceWorkerRegistration",
  "sessionStorage",
  "setInterval",
  "setTimeout",
  "ShadowRoot",
  "SharedWorker",
  "SourceBuffer",
  "SourceBufferList",
  "speechSynthesis",
  "SpeechSynthesisEvent",
  "SpeechSynthesisUtterance",
  "StaticRange",
  "status",
  "statusbar",
  "StereoPannerNode",
  "stop",
  "Storage",
  "StorageEvent",
  "StorageManager",
  "structuredClone",
  "styleMedia",
  "StyleSheet",
  "StyleSheetList",
  "SubmitEvent",
  "SubtleCrypto",
  "SVGAElement",
  "SVGAngle",
  "SVGAnimatedAngle",
  "SVGAnimatedBoolean",
  "SVGAnimatedEnumeration",
  "SVGAnimatedInteger",
  "SVGAnimatedLength",
  "SVGAnimatedLengthList",
  "SVGAnimatedNumber",
  "SVGAnimatedNumberList",
  "SVGAnimatedPreserveAspectRatio",
  "SVGAnimatedRect",
  "SVGAnimatedString",
  "SVGAnimatedTransformList",
  "SVGAnimateElement",
  "SVGAnimateMotionElement",
  "SVGAnimateTransformElement",
  "SVGAnimationElement",
  "SVGCircleElement",
  "SVGClipPathElement",
  "SVGComponentTransferFunctionElement",
  "SVGDefsElement",
  "SVGDescElement",
  "SVGDiscardElement",
  "SVGElement",
  "SVGEllipseElement",
  "SVGFEBlendElement",
  "SVGFEColorMatrixElement",
  "SVGFEComponentTransferElement",
  "SVGFECompositeElement",
  "SVGFEConvolveMatrixElement",
  "SVGFEDiffuseLightingElement",
  "SVGFEDisplacementMapElement",
  "SVGFEDistantLightElement",
  "SVGFEDropShadowElement",
  "SVGFEFloodElement",
  "SVGFEFuncAElement",
  "SVGFEFuncBElement",
  "SVGFEFuncGElement",
  "SVGFEFuncRElement",
  "SVGFEGaussianBlurElement",
  "SVGFEImageElement",
  "SVGFEMergeElement",
  "SVGFEMergeNodeElement",
  "SVGFEMorphologyElement",
  "SVGFEOffsetElement",
  "SVGFEPointLightElement",
  "SVGFESpecularLightingElement",
  "SVGFESpotLightElement",
  "SVGFETileElement",
  "SVGFETurbulenceElement",
  "SVGFilterElement",
  "SVGForeignObjectElement",
  "SVGGElement",
  "SVGGeometryElement",
  "SVGGradientElement",
  "SVGGraphicsElement",
  "SVGImageElement",
  "SVGLength",
  "SVGLengthList",
  "SVGLinearGradientElement",
  "SVGLineElement",
  "SVGMarkerElement",
  "SVGMaskElement",
  "SVGMatrix",
  "SVGMetadataElement",
  "SVGMPathElement",
  "SVGNumber",
  "SVGNumberList",
  "SVGPathElement",
  "SVGPatternElement",
  "SVGPoint",
  "SVGPointList",
  "SVGPolygonElement",
  "SVGPolylineElement",
  "SVGPreserveAspectRatio",
  "SVGRadialGradientElement",
  "SVGRect",
  "SVGRectElement",
  "SVGScriptElement",
  "SVGSetElement",
  "SVGStopElement",
  "SVGStringList",
  "SVGStyleElement",
  "SVGSVGElement",
  "SVGSwitchElement",
  "SVGSymbolElement",
  "SVGTextContentElement",
  "SVGTextElement",
  "SVGTextPathElement",
  "SVGTextPositioningElement",
  "SVGTitleElement",
  "SVGTransform",
  "SVGTransformList",
  "SVGTSpanElement",
  "SVGUnitTypes",
  "SVGUseElement",
  "SVGViewElement",
  "TaskAttributionTiming",
  "Text",
  "TextDecoder",
  "TextDecoderStream",
  "TextEncoder",
  "TextEncoderStream",
  "TextEvent",
  "TextMetrics",
  "TextTrack",
  "TextTrackCue",
  "TextTrackCueList",
  "TextTrackList",
  "TimeRanges",
  "ToggleEvent",
  "toolbar",
  "top",
  "Touch",
  "TouchEvent",
  "TouchList",
  "TrackEvent",
  "TransformStream",
  "TransformStreamDefaultController",
  "TransitionEvent",
  "TreeWalker",
  "UIEvent",
  "URL",
  "URLSearchParams",
  "ValidityState",
  "visualViewport",
  "VisualViewport",
  "VTTCue",
  "WaveShaperNode",
  "WebAssembly",
  "WebGL2RenderingContext",
  "WebGLActiveInfo",
  "WebGLBuffer",
  "WebGLContextEvent",
  "WebGLFramebuffer",
  "WebGLProgram",
  "WebGLQuery",
  "WebGLRenderbuffer",
  "WebGLRenderingContext",
  "WebGLSampler",
  "WebGLShader",
  "WebGLShaderPrecisionFormat",
  "WebGLSync",
  "WebGLTexture",
  "WebGLTransformFeedback",
  "WebGLUniformLocation",
  "WebGLVertexArrayObject",
  "WebSocket",
  "WheelEvent",
  "window",
  "Window",
  "Worker",
  "WritableStream",
  "WritableStreamDefaultController",
  "WritableStreamDefaultWriter",
  "XMLDocument",
  "XMLHttpRequest",
  "XMLHttpRequestEventTarget",
  "XMLHttpRequestUpload",
  "XMLSerializer",
  "XPathEvaluator",
  "XPathExpression",
  "XPathResult",
  "XRAnchor",
  "XRBoundedReferenceSpace",
  "XRCPUDepthInformation",
  "XRDepthInformation",
  "XRFrame",
  "XRInputSource",
  "XRInputSourceArray",
  "XRInputSourceEvent",
  "XRInputSourcesChangeEvent",
  "XRPose",
  "XRReferenceSpace",
  "XRReferenceSpaceEvent",
  "XRRenderState",
  "XRRigidTransform",
  "XRSession",
  "XRSessionEvent",
  "XRSpace",
  "XRSystem",
  "XRView",
  "XRViewerPose",
  "XRViewport",
  "XRWebGLBinding",
  "XRWebGLDepthInformation",
  "XRWebGLLayer",
  "XSLTProcessor",
];

/**
 * transform array to object to enable faster element check with in operator
 * @param array
 */
function array2TruthyObject(array: string[]): Record<string, true> {
  return array.reduce(
    (acc: Record<string, true>, key) => {
      acc[key] = true;
      return acc;
    },
    // Notes that babel will transpile spread operator to Object.assign({}, ...args), which will keep the prototype of Object in merged object,
    // while this result used as Symbol.unscopables, it will make properties in Object.prototype always be escaped from proxy sandbox as unscopables check will look up prototype chain as well,
    // such as hasOwnProperty, toString, valueOf, etc.
    // so we should use Object.create(null) to create a pure object without prototype chain here.
    Object.create(null) as Record<string, true>
  );
}

const accessingSpiedGlobals = ["document", "top", "parent", "eval"];
const overwrittenGlobals = ["window", "self", "globalThis", "hasOwnProperty"];

export const cachedGlobals = Array.from(
  new Set(
    without(
      globalsInES2015
        .concat(overwrittenGlobals)
        .concat("requestAnimationFrame"),
      ...accessingSpiedGlobals
    )
  )
);

export const cachedGlobalObjects = array2TruthyObject(cachedGlobals);

/*
 Variables who are impossible to be overwritten need to be escaped from proxy sandbox for performance reasons.
 But overwritten globals must not be escaped, otherwise they will be leaked to the global scope.
 see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables
 */

// 1. 从 cachedGlobals 中过滤掉 overwrittenGlobals 和 accessingSpiedGlobals 中的属性
// 2. 因为被重写的全局变量不能被沙箱逃逸，所以这里需要过滤掉 overwrittenGlobals
// 3. 其余不能被重写的全局变量可以被沙箱逃逸，这样可以提高性能

// {
//   "Array": true,
//   "ArrayBuffer": true,
//   "Boolean": true,
//   "constructor": true,
//   "DataView": true,
//   "Date": true,
//   "decodeURI": true,
//   "decodeURIComponent": true,
//   "encodeURI": true,
//   "encodeURIComponent": true,
//   "Error": true,
//   "escape": true,
//   "EvalError": true,
//   "Float32Array": true,
//   "Float64Array": true,
//   "Function": true,
//   "Infinity": true,
//   "Int16Array": true,
//   "Int32Array": true,
//   "Int8Array": true,
//   "isFinite": true,
//   "isNaN": true,
//   "isPrototypeOf": true,
//   "JSON": true,
//   "Map": true,
//   "Math": true,
//   "NaN": true,
//   "Number": true,
//   "Object": true,
//   "parseFloat": true,
//   "parseInt": true,
//   "Promise": true,
//   "propertyIsEnumerable": true,
//   "Proxy": true,
//   "RangeError": true,
//   "ReferenceError": true,
//   "Reflect": true,
//   "RegExp": true,
//   "Set": true,
//   "String": true,
//   "Symbol": true,
//   "SyntaxError": true,
//   "toLocaleString": true,
//   "toString": true,
//   "TypeError": true,
//   "Uint16Array": true,
//   "Uint32Array": true,
//   "Uint8Array": true,
//   "Uint8ClampedArray": true,
//   "undefined": true,
//   "unescape": true,
//   "URIError": true,
//   "valueOf": true,
//   "WeakMap": true,
//   "WeakSet": true,
//   "requestAnimationFrame": true
// }
export const unscopables = array2TruthyObject(
  without(cachedGlobals, ...accessingSpiedGlobals.concat(overwrittenGlobals))
);

export const cachedGlobalsInBrowser = array2TruthyObject(
  globalsInBrowser.concat(
    process.env.NODE_ENV === "test" ? ["mockNativeWindowFunction"] : []
  )
);
